[versions]
kotlin = "2.0.21"

[libraries]
protoc = { module = "com.google.protobuf:protoc", version = "4.28.3" }
protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version = "1.68.1" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
