/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package task.adapter.poc

import kotlin.test.Test
import kotlin.test.assertNotNull

class MainTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = Main()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
