name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

  keyvaluestore_ci:
    needs: prepare
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: keyvaluestore
    steps:
      - name: Install dependencies
        run: make deps
      - name: Run check
        run: make check
